# Generated by Django 3.0.1 on 2019-12-24 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HMCMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('designation', models.CharField(choices=[('NONE', '-Select-'), ('GENSEC', 'General Secretary'), ('WELFY', 'Welfare Secretary'), ('MESSI', 'Mess Convener'), ('CULTY', 'Cultural Secretary'), ('LITY', 'Literary Secretary'), ('TECHY', 'Technical Secretary'), ('SPORTY', 'Sports Secretary'), ('MENTY', 'Maintenance Secretary')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
