# Generated by Django 3.0.1 on 2019-12-24 17:13

import django.core.validators
from django.db import migrations, models
import umiam.models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0002_auto_20191224_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmcmember',
            name='iitg_email',
            field=models.EmailField(default='bhasker18@iitg.ac.in', max_length=254, validators=[umiam.models.is_iitg_email]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hmcmember',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
