# Generated by Django 3.0.1 on 2019-12-24 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0003_auto_20191224_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmcmember',
            name='iitg_email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(whitelist=['iitg.ac.in'])]),
        ),
    ]
