# Generated by Django 3.0.1 on 2019-12-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0004_auto_20191224_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmcmember',
            name='designation',
            field=models.CharField(choices=[(1, 'General Secretary'), (2, 'Welfare Secretary'), (3, 'Mess Convener'), (4, 'Cultural Secretary'), (5, 'Literary Secretary'), (6, 'Technical Secretary'), (7, 'Sports Secretary'), (8, 'Maintenance Secretary'), (9, 'Joint Maintenance Secretary')], max_length=50),
        ),
    ]
