# Generated by Django 3.0.1 on 2019-12-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0006_auto_20191225_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmcmember',
            name='designation',
            field=models.CharField(choices=[('General Secretary', 'General Secretary'), ('Welfare Secretary', 'Welfare Secretary'), ('Mess Convener', 'Mess Convener'), ('Cultural Secretary', 'Cultural Secretary'), ('Literary Secretary', 'Literary Secretary'), ('Technical Secretary', 'Technical Secretary'), ('Sports Secretary', 'Sports Secretary'), ('Maintenance Secretary', 'Maintenance Secretary')], max_length=50),
        ),
    ]
