# Generated by Django 3.0.1 on 2019-12-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0007_auto_20191225_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmcmember',
            name='priority',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
