# Generated by Django 3.0.1 on 2019-12-26 02:40

from django.db import migrations, models
import umiam.models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0009_auto_20191225_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmcmember',
            name='priority',
        ),
        migrations.AlterField(
            model_name='hmcmember',
            name='iitg_email',
            field=models.EmailField(max_length=254, validators=[umiam.models.is_iitg_email]),
        ),
    ]
