# Generated by Django 3.0.1 on 2019-12-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0010_auto_20191226_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmcmember',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
