# Generated by Django 3.0.1 on 2019-12-26 03:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0011_auto_20191226_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmcmember',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
