# Generated by Django 3.0.1 on 2019-12-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0013_auto_20191226_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_name', models.CharField(max_length=256)),
                ('achievement_description', models.CharField(blank=True, max_length=1024)),
                ('achievement_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=256)),
                ('event_description', models.CharField(blank=True, max_length=1024)),
                ('event_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
