# Generated by Django 3.0.1 on 2019-12-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umiam', '0014_achievement_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField()),
            ],
        ),
    ]
